### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [alimranahmed/zsh-imranic-themes#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by alimranahmed** [comment]
Hello, thanks for reaching out!

Added these two screenshot in the readme. 

<img width="738" alt="Kiss theme" src="https://github.com/user-attachments/assets/f58fef32-7a92-46a5-9bee-2cde69086632" />

<img width="738" alt="Kiss themse with github changes" src="https://github.com/user-attachments/assets/138cf6e0-e61d-4703-806b-2fa68d3a007e" />
